#!/bin/sh

set -f

for msg in $(notmuch search --output messages --sort oldest-first 'tag:new and tag:unread and folder:Revreso/INBOX'); do
	json="$(notmuch show --body=false --entire-thread=false --format=json "${msg}" | jq '.[0][0][0]')"
	subj="$(echo "$json" | jq -r '.headers.Subject')"
	from="$(echo "$json" | jq -r '.headers.From')"
	notify-send "$from" "$subj"
done

notmuch tag -new 'tag:new'
