#!/bin/sh
#
# Script to do all those things that are not solved by just changing text files

echo "Loading dconf settings"
dconf load / < "${HOME}/.config/dconf/overwrite.ini"

echo "Linking host-specific files"
ln -s "config.$(hostname)" "${HOME}/.config/mako/config" || true
