#!/bin/sh
#
# Script to do all those things that are not solved by just changing text files

echo "Loading dconf settings"
dconf load / < "${HOME}/.config/dconf/overwrite.ini"

echo "Linking host-specific files"
hostname="$(hostnamectl hostname)" || exit 1
ln -s "config.$hostname" "${HOME}/.config/mako/config" || true
