#!/bin/bash --norc

if [ -z "$DESKTOP_ENTRY_ID" ]; then
	appID="$(basename $1)"
else
	appID="$DESKTOP_ENTRY_ID"
fi

exec /usr/bin/systemd-run --user --scope -q \
	--slice=app.slice \
	--property=PartOf=graphical-session.target \
	--property=After=graphical-session.target \
	--unit="app-sway-${appID}-${RANDOM}.scope" \
	-- $@
