#!/bin/sh
#
# A small script to create a black-and-white PDF from a sane multi page project
# or scanimage PNM output. It assumes A4 paper size and 300 DPI resolution and
# expects the PNM files to be in the current directory, sorted alphanumerically.

# The 300 DPI resolution was chosen to fit the ADF of my scanner: Going a lot
# higher causes the scanner to stop periodically and wait for the data to be
# transferred (USB2 not being fast enough for this to happen in real time),
# going only a little bit higher causes the ADF to enter a slow mode which is
# ridiculously loud for some reason. Adjust if you scan with a higher DPI,
# though be aware that I don't know how well the PNG data size scales with
# resolution.
# Before this, I used 600dpi with grayscale and JPEG2000 compression, but apart
# from this causing the "loud mode", 1-bit color actually looks better on most
# scans and also compresses well with PNG (but not with JPEG2000).
PAPERSIZE="300dpi"

if [ $# -ne 1 ] && [ $# -ne 4 ]; then
	echo "Usage: $(basename $0) <output> [<title> <author> <subject>]"
	exit 1
fi

output="$1"
title="$2"
author="$3"
subject="$4"

tmpdir=$(mktemp -d)
parallel "convert {} -monochrome \"$tmpdir/{/.}.png\"" ::: ./*.pnm
if [ $# -eq 1 ]; then
	img2pdf -s $PAPERSIZE --output "$output" \
		$tmpdir/*.png
else
	img2pdf -s $PAPERSIZE --output "$output" \
		--title "$title" \
		--author "$author" \
		--creator "My scanner" \
		--subject "$subject" \
		$tmpdir/*.png
fi
rm $tmpdir/*.png
rmdir $tmpdir
